server:
  port: 80
zuul:
  routes:
    themes:
      path: /themes-management/**
      serviceId: themes-service
    news:
      path: /news-management/**
      serviceId: news-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
